'use client'

import { useState } from 'react'
import { ArrowUpRight, Bell, ChevronRight, CircleHelp, Droplets, Leaf, Menu, MoveUpRight, PackageCheck, Recycle, Route, Settings2, ShieldCheck, Sparkles, Sprout, Truck, Users, X, Zap } from 'lucide-react'
import { CircularFlow } from '@/components/circular-flow'
import { EsgOffering } from '@/components/esg-offering'
import { RouteOptimizer } from '@/components/route-optimizer'

const navItems = [
  { label: 'Home', icon: Leaf },
  { label: 'Circular flow', icon: Recycle },
  { label: 'ESG offering', icon: ShieldCheck },
  { label: 'Optimasi rute', icon: Route },
]
const prospectivePartners = [
  { type: 'HORECA', name: 'Hotel, restoran, dan kafe', detail: 'Sumber organik yang ingin dikelola lebih rapi.' },
  { type: 'PENGOLAH', name: 'Pengolah organik lokal', detail: 'Mengubah material menjadi input yang berguna.' },
  { type: 'PETERNAKAN', name: 'Peternakan sekitar', detail: 'Penerima nilai dari rantai yang lebih pendek.' },
]
function StatCard({ icon: Icon, label, value, note, accent }: { icon: typeof Leaf; label: string; value: string; note: string; accent: string }) { return <article className={`terra-stat ${accent}`}><div className="terra-stat-top"><span className="terra-icon"><Icon aria-hidden="true" /></span><MoveUpRight aria-hidden="true" /></div><p>{label}</p><strong>{value}</strong><small>{note}</small></article> }
function FlowStep({ number, title, detail, icon: Icon }: { number: string; title: string; detail: string; icon: typeof Leaf }) { return <div className="flow-step"><span className="flow-number">{number}</span><div className="flow-icon"><Icon aria-hidden="true" /></div><div><strong>{title}</strong><p>{detail}</p></div></div> }
function HomeContent({ notify }: { notify: (message: string) => void }) { return <>
  <section className="terra-hero"><div className="hero-copy"><span className="terra-badge"><span /> EKONOMI SIRKULAR INDONESIA</span><h2>Rooted in Earth,<br /><i>Reaching for the Ninth.</i></h2><p>TERRANAVA membantu bisnis mengelola limbah organik dengan cara yang lebih jelas, terukur, dan punya nilai. Dari dapur, kembali ke tanah, lalu tumbuh menjadi manfaat baru.</p><div className="hero-actions"><button className="terra-button primary" onClick={() => notify('Terima kasih. Tim TERRANAVA akan menghubungi Anda.')}>Mulai bicara dengan kami <ArrowUpRight /></button><button className="terra-text-button" onClick={() => document.getElementById('origin')?.scrollIntoView({ behavior: 'smooth' })}>Kenali TERRANAVA <ChevronRight /></button></div></div><div className="hero-orbit" aria-label="Ilustrasi sistem ekonomi sirkular"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit-core"><Sprout /><span>09</span></div><span className="orbit-label label-one">ORGANIK</span><span className="orbit-label label-two">NILAI</span><span className="orbit-label label-three">BUKTI</span></div></section>
  <section className="terra-stats"><StatCard icon={Leaf} label="Organik dialihkan" value="12,84 t" note="Contoh capaian dalam satu periode" accent="green" /><StatCard icon={Droplets} label="Jejak air terselamatkan" value="48,2 kL" note="Perkiraan dari aktivitas terukur" accent="blue" /><StatCard icon={Truck} label="Rantai yang disiapkan" value="24 titik" note="HORECA · pengolah · peternakan" accent="orange" /><StatCard icon={Sparkles} label="Kesiapan ESG" value="78 / 100" note="Gambaran awal untuk evaluasi" accent="violet" /></section>
  <section className="terra-grid"><article className="terra-panel origin-panel" id="origin"><div className="panel-label"><span>01 / Asal nama</span><span className="panel-line" /></div><h3>Nama yang punya<br />arah.</h3><p><b>Terra</b> berarti bumi. <b>Nava</b> berarti sembilan — angka tertinggi, sekaligus simbol sembilan pilar ekonomi sirkular yang menjadi arah kerja kami.</p><div className="origin-note"><span>09</span><div><strong>Sembilan adalah arah yang kami tuju.</strong><small>Bukan sekadar angka, tetapi dorongan untuk membangun sistem yang lebih utuh dan berdampak.</small></div></div><button className="panel-link" onClick={() => notify('Cerita TERRANAVA siap dibaca')}>Baca cerita kami <ArrowUpRight /></button></article><article className="terra-panel flow-panel"><div className="panel-label"><span>02 / Alur kerja</span><span className="live-chip"><i /> Berjalan</span></div><h3>Satu aliran,<br /><i>empat titik nilai.</i></h3><div className="flow-list"><FlowStep number="01" title="HORECA" detail="Pisahkan dari sumbernya" icon={PackageCheck} /><FlowStep number="02" title="TERRANAVA" detail="Jemput dan catat dengan rapi" icon={Truck} /><FlowStep number="03" title="PENGOLAH" detail="Olah menjadi input baru" icon={Recycle} /><FlowStep number="04" title="LAHAN HIDUP" detail="Kembali memberi manfaat" icon={Sprout} /></div><div className="flow-footer"><span>Pembaruan terakhir 08:42 WIB</span><button onClick={() => notify('Data alur diperbarui')}>Perbarui <Zap /></button></div></article></section>
  <section className="terra-panel partner-panel"><div className="panel-label"><span>03 / Ekosistem yang kami bangun</span><span className="panel-line" /></div><div className="partner-heading"><div><h3>Mitra yang ingin<br /><i>kami tumbuhkan.</i></h3><p>Setiap rantai dimulai dari percakapan. Berikut gambaran pihak yang ingin kami hubungkan — bukan daftar kontrak yang sudah berjalan.</p></div><Users /></div><div className="partner-grid">{prospectivePartners.map((partner) => <article className="partner-card" key={partner.type}><span>{partner.type}</span><h4>{partner.name}</h4><p>{partner.detail}</p></article>)}</div></section>
  <section className="terra-mission"><div><span className="terra-kicker">Arah TERRANAVA</span><h3>Industri hijau yang<br /><i>menguntungkan semua.</i></h3></div><div className="mission-copy"><p>Visi kami adalah menjadi pelopor industri hijau Indonesia — mengubah limbah organik menjadi nilai ekonomi berkelanjutan melalui sistem ekonomi sirkular yang terstandar dan terukur.</p><button className="terra-text-button" onClick={() => notify('Visi dan misi TERRANAVA dibuka')}>Lihat visi dan misi <ChevronRight /></button></div></section>
</> }
function ContactModal({ onClose }: { onClose: () => void }) { return <div className="terra-modal-backdrop"><div className="terra-modal" role="dialog" aria-modal="true"><div className="terra-modal-head"><div><span className="terra-kicker">MARI BICARA</span><h2>Mulai dari obrolan kecil.</h2></div><button onClick={onClose} aria-label="Tutup"><X /></button></div><p>Ceritakan sedikit tentang operasional Anda. Kami akan bantu mencari langkah yang paling masuk akal.</p><label>Nama<input placeholder="Nama Anda" /></label><label>Email kerja<input placeholder="nama@perusahaan.com" type="email" /></label><button className="terra-button primary full" onClick={onClose}>Kirim minat <ArrowUpRight /></button></div></div> }

export default function EsgDashboard() {
  const [activeNav, setActiveNav] = useState('Home'); const [menuOpen, setMenuOpen] = useState(false); const [showModal, setShowModal] = useState(false); const [toast, setToast] = useState('')
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2600) }
  const openChat = () => setShowModal(true)
  return <div className="terra-app"><aside className={`terra-sidebar ${menuOpen ? 'is-open' : ''}`}><div className="terra-brand"><img src="/terranava-logo.jpg" alt="Logo TERRANAVA INDONESIA" /><div><strong>TERRANAVA</strong><span>INDONESIA</span></div></div><div className="terra-context"><span className="context-orb">TI</span><span><b>Ruang dampak</b><small>Jakarta · Indonesia</small></span><ChevronRight /></div><nav className="terra-nav" aria-label="Navigasi utama"><span className="terra-nav-label">Menu</span>{navItems.map(({ label, icon: Icon }) => <button className={activeNav === label ? 'active' : ''} key={label} onClick={() => { setActiveNav(label); setMenuOpen(false) }}><Icon /><span>{label}</span>{label === 'Circular flow' && <em>LIVE</em>}</button>)}</nav><div className="terra-sidebar-bottom"><button onClick={() => notify('Pusat bantuan TERRANAVA dibuka')}><CircleHelp />Pusat bantuan</button><button onClick={() => notify('Pengaturan ruang kerja dibuka')}><Settings2 />Pengaturan ruang kerja</button><div className="terra-user"><span className="user-avatar">RA</span><span><b>Rani Adelia</b><small>Impact lead</small></span><button aria-label="Notifikasi" onClick={() => notify('Tidak ada notifikasi baru')}><Bell /></button></div></div></aside><main className={`terra-main ${activeNav === 'Optimasi rute' ? 'is-route' : ''}`}>{activeNav === 'Optimasi rute' ? <RouteOptimizer onBack={() => setActiveNav('Home')} /> : <><header className="terra-header"><button className="terra-mobile-menu" aria-label="Buka navigasi" onClick={() => setMenuOpen(!menuOpen)}><Menu /></button><div><span className="terra-kicker">TERRANAVA / {activeNav}</span><h1>{activeNav === 'Home' ? 'Selamat datang di TERRANAVA' : activeNav}</h1></div><div className="terra-header-actions"><span className="live-indicator"><i /> Sistem aktif</span><button className="terra-notification" aria-label="Notifikasi" onClick={() => notify('Tidak ada notifikasi baru')}><Bell /><i /></button><span className="terra-header-avatar">RA</span></div></header>{activeNav === 'Home' && <HomeContent notify={notify} />}{activeNav === 'ESG offering' && <EsgOffering onOpenChat={openChat} />}{activeNav === 'Circular flow' && <CircularFlow onBack={() => setActiveNav('Home')} />}</>}</main>{toast && <div className="terra-toast" role="status"><Leaf />{toast}</div>}{showModal && <ContactModal onClose={() => setShowModal(false)} />}</div>
}
